<?php

namespace Container1PdtVk2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRandomSpellCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RandomSpellCommand' shared autowired service.
     *
     * @return \App\Command\RandomSpellCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RandomSpellCommand.php';

        $container->privates['App\\Command\\RandomSpellCommand'] = $instance = new \App\Command\RandomSpellCommand(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setName('app:random-spell');

        return $instance;
    }
}
