<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1PdtVk2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1PdtVk2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1PdtVk2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1PdtVk2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1PdtVk2\App_KernelDevDebugContainer([
    'container.build_hash' => '1PdtVk2',
    'container.build_id' => '80b0d61e',
    'container.build_time' => 1739816814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1PdtVk2');
